/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_position_example_controller:
        type: franka_example_controllers/JointPositionExampleController

      joint_velocity_example_controller:
        type: franka_example_controllers/JointVelocityExampleController

      joint_impedance_example_controller:
        type: franka_example_controllers/JointImpedanceExampleController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      mobile_fr3_duo_joint_impedance_example_controller:
        type: franka_example_controllers/MobileFr3DuoJointImpedanceExampleController
      
      gravity_compensation_example_controller:
        type: franka_example_controllers/GravityCompensationExampleController

      swerve_ik_controller:
        type: franka_mobile/SwerveIKController
      
      swerve_drive_controller:
        type: franka_mobile/SwerveDriveController

      model_example_controller:
        type: franka_example_controllers/ModelExampleController

      cartesian_impedance_example_controller:
        type: franka_example_controllers/CartesianImpedanceExampleController

  joint_velocity_example_controller:
    ros__parameters:
      robot_type: "fr3"
      gazebo: true

  joint_impedance_example_controller:
    ros__parameters:
      robot_type: "fr3"
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5

  swerve_drive_controller:
    ros__parameters:
      command_interface_prefix: swerve_ik_controller/
      state_interface_prefix: tmrv0_2_
      wheel_1_link_name: argo_drive_front_link
      wheel_2_link_name: argo_drive_rear_link

      linear:
        x:
          has_velocity_limits    : true
          max_velocity           : 0.50  # m/s
          min_velocity           : -0.50 # m/s
          has_acceleration_limits: true
          max_acceleration       : 1.0  # m/s^2
          min_acceleration       : -1.0 # m/s^2
          has_jerk_limits        : false
          max_jerk               : 10.0  # m/s^3
          min_jerk               : -10.0  # m/s^3
        y:
          has_velocity_limits    : true
          max_velocity           : 0.5  # m/s
          min_velocity           : -0.5 # m/s
          has_acceleration_limits: true
          max_acceleration       : 1.0  # m/s^2
          min_acceleration       : -1.0 # m/s^2
          has_jerk_limits        : false
          max_jerk               : 10.0  # m/s^3
          min_jerk               : -10.0  # m/s^3
      angular:
        z:
          has_velocity_limits    : true
          max_velocity           : 1.7  # rad/s
          has_acceleration_limits: true
          max_acceleration       : 1.0  # rad/s^2
          min_acceleration       : -1.0  # rad/s^2
          has_jerk_limits        : false
          max_jerk               : 10.0  # rad/s^3
          min_jerk               : -10.0  # rad/s^3
    

  swerve_ik_controller:
    ros__parameters:
      prefix: "tmrv0_2_"
      wheel_1_link_name: argo_drive_front_link
      wheel_2_link_name: argo_drive_rear_link

  model_example_controller:
    ros__parameters:
      robot_type: 'fr3'
      arm_prefix: ''
